Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  #config.vm.network "forwarded_port", guest: 8443, host: 8443
  #config.vm.network "public_network"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "service-fabric-ubuntu"
    vb.cpus = 4
    vb.memory = "4096"
  end
  config.vm.provision "shell", inline: $script
end

$script = <<-SCRIPT
sudo apt update
sudo apt upgrade -y
sudo apt install apt-transport-https ca-certificates curl software-properties-common -yaml
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt update
sudo apt install docker-ce -y
sudo usermod -aG docker $USER
sudo docker container run hello-world
sudo apt-get install git -y
git clone https://github.com/Microsoft/service-fabric.git
cd ./service-fabric
sudo ./tools/build/builddocker.sh
SCRIPT
