Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine37"
  config.vm.network "forwarded_port", guest: 8443, host: 8443
  #config.vm.network "public_network"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "wigo4it-rancher2"
    vb.cpus = 4
    vb.memory = "4096"
  end
  config.vm.provision "shell", inline: $script
end

$script = <<-SCRIPT
sudo apk add docker
sudo apk add openrc --no-cache
sudo rc-update add docker boot
sudo service docker start
sleep 10
sudo docker run --name=rancher -d --restart=unless-stopped -p 8085:80 -p 8443:443 -v /var/lib/rancher:/var/lib/rancher rancher/rancher:v2.0.6
SCRIPT
